spring:
  application:
    name: SubThree

  # H2 Database ??
  datasource:
    driver-class-name: org.h2.Driver
#    url: 'jdbc:h2:mem:test'   # H2 DB ?? ?? (In-Memory Mode)
    url: jdbc:h2:./data/demo    # H2 DB ?? ?? (Embedded Mode)
    username: sa        # H2 DB ?? ID (??? ??)
    password:           # H2 DB ?? PW (??? ??)

  # H2 Console ??
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??
      path: /h2-console       # H2 Console ?? ??

  # JPA ??
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate       # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # ?? ?? ?? (??)
        show_sql: true        # ?? ?? ??

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e60cb252426927a823be79574f6d06b9
            client-secret: OXtTw9cZWRUuRqbxcoXApSD0TwtAFLEw
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            #            user-name-attribute: kakao_account
            user-name-attribute: id
